# modules/lua/logging/logging/Makefile

LRUN= ../../../..

include $(LRUN)/config/make/Config.mak
INSTALL_SUBDIR=$(INSTALL_DIR_LUA)/logging
LUA_SRC=console.lua email.lua file.lua socket.lua sql.lua
include $(LRUN)/config/make/ScriptModule.mak
